/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.calculadora.cientifica;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.JOptionPane;

/**
 *
 * @author trian
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public view() {
        initComponents();
        // Centrar JFrame
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnParentecisIzquierdo = new javax.swing.JButton();
        btnParentecesisDerecho = new javax.swing.JButton();
        btnElevadoAlCuadrado = new javax.swing.JButton();
        btnElevadoAlCubo = new javax.swing.JButton();
        btnElevadoALaN = new javax.swing.JButton();
        btnSen = new javax.swing.JButton();
        btnCoseno = new javax.swing.JButton();
        btnTangente = new javax.swing.JButton();
        btnRaizCuadrada = new javax.swing.JButton();
        btnRaizCubica = new javax.swing.JButton();
        btnLogBase10 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnLogBaseE = new javax.swing.JButton();
        btnGradosARadianas = new javax.swing.JButton();
        btmRadianesAGrados = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOperaciones = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCerrar.setBackground(new java.awt.Color(255, 51, 102));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(51, 0, 255));
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setText("-");
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnSuma.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnDividir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnMultiplicar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnMultiplicar.setText("*");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnParentecisIzquierdo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnParentecisIzquierdo.setText("(");
        btnParentecisIzquierdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentecisIzquierdoActionPerformed(evt);
            }
        });

        btnParentecesisDerecho.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnParentecesisDerecho.setText(")");
        btnParentecesisDerecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentecesisDerechoActionPerformed(evt);
            }
        });

        btnElevadoAlCuadrado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnElevadoAlCuadrado.setText("<html>x<sup>2</sup></html>");
        btnElevadoAlCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElevadoAlCuadradoActionPerformed(evt);
            }
        });

        btnElevadoAlCubo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnElevadoAlCubo.setText("<html>x<sup>3</sup></html>");
        btnElevadoAlCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElevadoAlCuboActionPerformed(evt);
            }
        });

        btnElevadoALaN.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnElevadoALaN.setText("<html>x<sup>n</sup></html>");
        btnElevadoALaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElevadoALaNActionPerformed(evt);
            }
        });

        btnSen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnSen.setText("sen(x)");
        btnSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenActionPerformed(evt);
            }
        });

        btnCoseno.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCoseno.setText("cos(x)");
        btnCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosenoActionPerformed(evt);
            }
        });

        btnTangente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnTangente.setText("tan(x)");
        btnTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangenteActionPerformed(evt);
            }
        });

        btnRaizCuadrada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnRaizCuadrada.setText("√x");
        btnRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizCuadradaActionPerformed(evt);
            }
        });

        btnRaizCubica.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnRaizCubica.setText("<html>&#8731;x</html>");
        btnRaizCubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizCubicaActionPerformed(evt);
            }
        });

        btnLogBase10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnLogBase10.setText("<html>log<sub>10</sub>(x)</html>");
        btnLogBase10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogBase10ActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(0, 0, 204));
        btnIgual.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnLogBaseE.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnLogBaseE.setText("<html>log<sub>e</sub>(x)</html>");
        btnLogBaseE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogBaseEActionPerformed(evt);
            }
        });

        btnGradosARadianas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnGradosARadianas.setText("Grad to Rad");
        btnGradosARadianas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradosARadianasActionPerformed(evt);
            }
        });

        btmRadianesAGrados.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btmRadianesAGrados.setText("Rad to Grad");
        btmRadianesAGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRadianesAGradosActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 51, 102));
        btnLimpiar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("C");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtOperaciones.setEditable(false);
        txtOperaciones.setColumns(20);
        txtOperaciones.setRows(5);
        jScrollPane1.setViewportView(txtOperaciones);

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        btn1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPunto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnPi.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnPi.setText("PI");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btmRadianesAGrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGradosARadianas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnElevadoAlCubo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnElevadoALaN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnElevadoAlCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRaizCubica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogBaseE, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(375, 375, 375))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnSen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCoseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(375, 375, 375))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnParentecisIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnParentecesisDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLogBase10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                                    .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addContainerGap())))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuma)
                    .addComponent(btnResta)
                    .addComponent(btnMultiplicar)
                    .addComponent(btnDividir)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnElevadoALaN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElevadoAlCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRaizCubica)
                                    .addComponent(btnElevadoAlCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRaizCuadrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLogBaseE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSen)
                                    .addComponent(btnGradosARadianas)
                                    .addComponent(btnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btmRadianesAGrados)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnParentecisIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnParentecesisDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogBase10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4)
                            .addComponent(btn5)
                            .addComponent(btn6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn9)
                            .addComponent(btn8)
                            .addComponent(btn7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btn0)
                            .addComponent(btnIgual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPunto)
                            .addComponent(btnPi))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // Cerramos la calculadora (programa)
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de Cerrar el programa?");
        if (opcion == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        // Minimizamos el programa
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "+");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "-");
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "/");
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "*");
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnParentecesisDerechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentecesisDerechoActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + ")");
    }//GEN-LAST:event_btnParentecesisDerechoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        if (!txtOperaciones.getText().isEmpty()) {
            // Crear un ScriptEngine para evaluar expresiones JavaScript
            ScriptEngine engine = new ScriptEngineManager().getEngineByName("JavaScript");
            String operacion = txtOperaciones.getText();
            try {
                Object result = engine.eval(operacion);
                txtResultado.setText(result.toString());
            } catch (ScriptException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(null,
                        "Ocurrio un error al realizar la operacion, valide la operacion suministrada", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnParentecisIzquierdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentecisIzquierdoActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "(");
    }//GEN-LAST:event_btnParentecisIzquierdoActionPerformed

    private void btnElevadoAlCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElevadoAlCuadradoActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el valor de X");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long num1 = null;
            Long num2 = 2L;
            try {
                num1 = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            String op = "Math.pow(" + num1 + ", " + num2 + ")";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnElevadoAlCuadradoActionPerformed

    private void btnElevadoAlCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElevadoAlCuboActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el valor de X");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long num1 = null;
            Long num2 = 3L;
            try {
                num1 = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            String op = "Math.pow(" + num1 + ", " + num2 + ")";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnElevadoAlCuboActionPerformed

    private void btnSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el angulo en grados");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long angulo = null;
            try {
                angulo = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            // Convertir el ángulo a radianes
            Double anguloEnRadianes = Math.toRadians(angulo);
            String op = "Math.sin(" + anguloEnRadianes + ")";

            /* TODO ajustar para que de los calculos como en la imagen!
            ScriptEngine engine = new ScriptEngineManager().getEngineByName("JavaScript");
            Object result;
            Double valor = null;
            try {
                result = engine.eval(op);
                valor = (double) result;
            } catch (ScriptException ex) {
                Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Definir un umbral para considerar como cero
           
            double threshold = 1e-10;
            if (Math.abs(valor) < threshold) {
                JOptionPane.showMessageDialog(null, "El coseno de " + angulo + " grados es aproximadamente 0");
            } else {
                JOptionPane.showMessageDialog(null, "El coseno de " + angulo + " grados es: " + valor);
            }
             
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + valor + ")");
             */
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnSenActionPerformed

    private void btnCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosenoActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el angulo en grados");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long angulo = null;
            try {
                angulo = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            // Convertir el ángulo a radianes
            Double anguloEnRadianes = Math.toRadians(angulo);
            JOptionPane.showMessageDialog(null, "El valor del angulo convertido en radianes es " + anguloEnRadianes);

            String op = "Math.cos(" + anguloEnRadianes + ")";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnCosenoActionPerformed

    private void btnTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangenteActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el angulo en grados");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long angulo = null;
            try {
                angulo = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            // Convertir el ángulo a radianes
            Double anguloEnRadianes = Math.toRadians(angulo);
            JOptionPane.showMessageDialog(null, "El valor del angulo convertido en radianes es " + anguloEnRadianes);

            String op = "Math.tan(" + anguloEnRadianes + ")";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }    }//GEN-LAST:event_btnTangenteActionPerformed

    private void btnRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizCuadradaActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el valor de X");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long num1 = null;
            try {
                num1 = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            String op = "Math.sqrt(" + num1 + ")";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnRaizCuadradaActionPerformed

    private void btnRaizCubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizCubicaActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el valor de X");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long num1 = null;
            try {
                num1 = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            String op = "Math.pow(" + num1 + ", 1/3)";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnRaizCubicaActionPerformed

    private void btnElevadoALaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElevadoALaNActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el valor de X");
        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long num1 = null;
            Long num2 = null;
            try {
                num1 = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            String valorN = JOptionPane.showInputDialog("Por favor, introduce el valor de N");
            if (valorN == null || valorN.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se introdujo el valor de N. El valor es nulo o vacío.");
            } else {
                try {
                    num2 = Long.parseLong(valorN);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Valor de N es inválida. Por favor, introduce un número válido.");
                }
            }
            String op = "Math.pow(" + num1 + ", " + num2 + ")";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnElevadoALaNActionPerformed

    private void btnLogBase10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogBase10ActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el valor de X");

        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long num1 = null;
            try {
                num1 = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            String op = "Math.log(" + num1 + ") / Math.log(10)";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnLogBase10ActionPerformed

    private void btnLogBaseEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogBaseEActionPerformed
        String valorX = JOptionPane.showInputDialog("Por favor, introduce el valor de X");

        if (valorX == null || valorX.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo el valor de X. El valor es nulo o vacío.");
        } else {
            Long num1 = null;
            try {
                num1 = Long.parseLong(valorX);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor de X es inválida. Por favor, introduce un número válido.");
            }

            String op = "Math.log(" + num1 + ")";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnLogBaseEActionPerformed

    private void btnGradosARadianasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradosARadianasActionPerformed
        String grados = JOptionPane.showInputDialog("Por favor, introduce los grados que deseas convertir a radianes");

        if (grados == null || grados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo los grados. El valor es nulo o vacío.");
        } else {
            Long valor = null;
            try {
                valor = Long.parseLong(grados);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Grados es inválida. Por favor, introduce un número válido.");
            }

            String op = "((" + valor + " * Math.PI) / 180)";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btnGradosARadianasActionPerformed

    private void btmRadianesAGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRadianesAGradosActionPerformed
        String radianes = JOptionPane.showInputDialog("Por favor, introduce los radianes que deseas convertir a grados");

        if (radianes == null || radianes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se introdujo los radianes. El valor es nulo o vacío.");
        } else {
            Long valor = null;
            try {
                valor = Long.parseLong(radianes);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "radianes es inválida. Por favor, introduce un número válido.");
            }

            String op = valor + " * (180 / Math.PI) ";
            this.txtOperaciones.setText(this.txtOperaciones.getText() + "(" + op + ")");
        }
    }//GEN-LAST:event_btmRadianesAGradosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtOperaciones.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + ".");
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        this.txtOperaciones.setText(this.txtOperaciones.getText() + Math.PI);
    }//GEN-LAST:event_btnPiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmRadianesAGrados;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCoseno;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnElevadoALaN;
    private javax.swing.JButton btnElevadoAlCuadrado;
    private javax.swing.JButton btnElevadoAlCubo;
    private javax.swing.JButton btnGradosARadianas;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLogBase10;
    private javax.swing.JButton btnLogBaseE;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnParentecesisDerecho;
    private javax.swing.JButton btnParentecisIzquierdo;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaizCuadrada;
    private javax.swing.JButton btnRaizCubica;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSen;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTangente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtOperaciones;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
